[package]
name = "trust"
version = "0.1.0"
authors = ["Harshit Pant <pantharshit00@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tun = "0.5"
etherparse="0.9.0"
